services:
  backend:
    build:
      context: ./junkdrawer
      dockerfile: Dockerfile
      network: host
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - junkdrawer-network
  
  whisper-api:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: whisper
    environment:
      - WHISPER_MODEL=small
      - LANGUAGE=es
    restart: unless-stopped
    networks:
      - junkdrawer-network

networks:
  junkdrawer-network:
    driver: bridge